# Generated by Django 3.0.3 on 2020-09-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_voca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voca',
            old_name='user_id',
            new_name='user',
        ),
    ]
