# Generated by Django 3.0.3 on 2020-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200923_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voca',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
