# Generated by Django 3.0.3 on 2020-09-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200924_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voca',
            name='date',
        ),
    ]
