# Generated by Django 3.0.3 on 2020-09-23 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_voca_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voca',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
