# Generated by Django 3.0.3 on 2020-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_voca_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voca',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
